# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Dasik' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Dasik
  pod 'FSCalendar' 

  target 'DasikTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DasikUITests' do
    # Pods for testing
  end

end
